### ISSUE TITLE
rsync exited with code 127

### ISSUE THREAD

**Issue by paddingme** [jerrysu/gulp-rsync#32]
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Error: rsync exited with code 127
    at ChildProcess.<anonymous> (/Users/paddingme/Documents/paddingme's work/front/xsczda/client/node_modules/gulp-rsync/rsync.js:110:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

OS X EI Capitan

**Comment by frob** [comment]
I think error code 127 is that rsync wasn't on the host. It would need to be on the both source and destination machines.

**Comment by sinpaout** [comment]
I have same problem and installing rsync on the Host was resolved for me.

**Comment by frob** [comment]
This can be closed.

**Comment by BiDbMAK** [comment]
I have the same problem on bitbucket pipelines and installing rsync was resolved for me.
Here is my bitbucket-pipelines.yml config:
image: node:8.9.1

pipelines:
  default:
    - step:
        script:
          - echo "deploy with peace and harmony"

  branches:
      master:
        - step:
            caches:
            - node
            script:
            - apt-get update && apt-get -qq install rsync
            - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
            - export PATH=$HOME/.yarn/bin:$PATH
            - yarn
            - yarn global add gulp-cli rsync
            - gulp deploy --staging
